name: Game of Life

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          git clone https://github.com/kevinlawler/kona.git
          cd kona
          make -j$(nproc)

      - run: echo '' | ./kona/k 1.k
